#!/usr/bin/env python
# vim: set expandtab ts=4 sw=4:

# Author: Ian Gable <igable@uvic.ca>

import subprocess
import re
import sys
from optparse import OptionParser

def main():
    jumbo_size = 8000
    regular_size = 64



    parser = OptionParser(usage="%prog -r REGULARMTU -j JUMBOMTU -f HOSTLISTFILE",version = "%prog 0.1")
    
    parser.add_option("-r", "--regular-mtu", dest="regular_size",
                                            help="regular packet size", metavar="REGULARMTU")
   
    parser.add_option("-j", "--jumbo-mtu", dest="jumbo_size",
                                            help="jumbo packet size", metavar="JUMBOMTU")
    
    parser.add_option("-f", "--file", dest="file",
                                            help="file containing a list of hosts", metavar="HOSTLISTFILE")
    
    (options, args) = parser.parse_args()
    
    if not options.file:
        parser.print_help()
        parser.error("You must specify a list of hosts to test with -f or --file")
    if options.regular_size:
        regular_size = int(options.regular_size)
    if options.jumbo_size:
        jumbo_size = int(options.jumbo_size)
    
  
    site_list = options.file
    
    try:
        file = open(site_list,'r')
    except IOError:
        sys.stderr.write("Does %s exist, and is it readable?\n" % site_list)
        sys.exit()
    
    loss = ""
    jumbo_loss = ""
    
    explanation = """
    Show which hosts are reachable with jumbo frame packets.
    
    We test by pinging with a 64 byte packet and then an 8000 byte
    packet. If pinging with that size is successful the value will
    printed
    
    Small_Packet Jumbo_Packet Hostname
    """
    #print explanation
    
    
    for line in file:
           
        ping_process = subprocess.Popen([r"ping", "-M", "do", "-s", str(regular_size), "-c", "4", line.strip()],stdout=subprocess.PIPE,stderr=subprocess.PIPE)
        output,error = ping_process.communicate();
        loss = re.search("Unreachable",output)
        
        if not loss:
            jumbo_ping_process = subprocess.Popen([r"ping", "-M", "do", "-s", str(jumbo_size), "-c", "4", line.strip()],stdout=subprocess.PIPE,stderr=subprocess.PIPE)
            jumbo_output, jumbo_error = jumbo_ping_process.communicate();
            jumbo_frag = re.search("Frag",jumbo_output)
            jumbo_loss =  re.search('100% packet loss', jumbo_output)
        
        #loss, mean_rtt, average_rtt = ping.quiet_ping(line.strip(),2,4,regular_size)
        #jumbo_loss, jumbo_mean_rtt, jumbo_average_rtt = ping.quiet_ping(line.strip(),2,4,jumbo_size)
    
        if loss:
            print " x    x %s unreachable" % (line.strip())
        elif jumbo_frag:
            print "%i    x %s fragmented" % (regular_size, line.strip().ljust(35))
        elif jumbo_loss:
            print "%i    x %s dropped" % (regular_size, line.strip().ljust(35))
        else:
            print "%i %i %s jumbo" % (regular_size,jumbo_size, line.strip().ljust(35))
        sys.stdout.flush()    
        jumbo_loss = ""
        loss = ""
    
    file.close()
 

main()   
